# Build Workflow / Stage
name: Build
run-name: 'Build triggered by @${{ github.actor }} on branch ${{ github.head_ref || github.ref_name }} for ${{ github.event_name }}'

on:
  push: # Pre Merge for default branches
    branches: [ main, development ]
  pull_request: # Pre Merge for PRs
    branches: [ main, development ]
    types: [ opened, reopened, synchronize]

# Jobs under Build Workflow
jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Load Service file
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json

      - name: Grant Execute Permissions for Gradlew
        run: chmod +x gradlew

      - name: Execute Gradle Debug Build
        run: ./gradlew assembleDebug -s
